name: CI notify

on:
  workflow_run:
    workflows: ["CI release"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "channel": "C01JDQES01G",
            "text": "GitHub Action failed",
            "blocks": [
              {	
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "🚀 Mimi SDK for iOS v#{version} is now available",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://github.com/MimiHearingTechnologies/SDK-iOS-Binaries-Test/releases/tag/9.1.0|*View on GitHub*>"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
