name: CI release

on:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      sdk_version: ${{ steps.set_env_variables.outputs.sdk_version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - id: set_env_variables
      name: Set environment variables
      run: |
        echo "sdk_version=$(grep -oP 'MIMI_SDK_VERSION=\K[^ ]+' Version.config)" >> "$GITHUB_OUTPUT"
      working-directory: ${{ github.workspace }}

    - name: Download MimiSDK zip from draft release
      run: |
        gh release download $MIMI_SDK_VERSION --pattern "MimiSDK-$MIMI_SDK_VERSION.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MIMI_SDK_VERSION: ${{steps.set_env_variables.outputs.sdk_version}}
      working-directory: ${{ github.workspace }}

    - name: Unarchive zip file
      run: |
        rm -rf artifacts
        mkdir artifacts
        unzip MimiSDK-$MIMI_SDK_VERSION.zip -d artifacts
      env:
        MIMI_SDK_VERSION: ${{steps.set_env_variables.outputs.sdk_version}}
      working-directory: ${{ github.workspace }}

    - name: Remove zip file and unnecessary files
      run: |
        rm -rf MimiSDK-$MIMI_SDK_VERSION.zip Version.config
      env:
        MIMI_SDK_VERSION: ${{steps.set_env_variables.outputs.sdk_version}}
      working-directory: ${{ github.workspace }}

    - name: Commit changes to release branch
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "Release [skip ci]"
        git push
      env:
        token: ${{ secrets.GH_TOKEN }}
      working-directory: ${{ github.workspace }}

    # - name: Merge changes into main branch with squash
    #   run: |
    #     git checkout main
    #     git pull origin main
    #     git merge --no-ff --no-commit release/$MIMI_SDK_VERSION
    #     git commit -m "Release v$MIMI_SDK_VERSION [skip ci]"
    #     git push
    #   env:
    #     token: ${{ secrets.GH_TOKEN }}
    #     MIMI_SDK_VERSION: ${{steps.set_env_variables.outputs.sdk_version}}
    #   working-directory: ${{ github.workspace }}

    - name: Delete release branch
      run: |
        git push origin --delete release/$MIMI_SDK_VERSION
      env:
        token: ${{ secrets.GH_TOKEN }}
        MIMI_SDK_VERSION: ${{steps.set_env_variables.outputs.sdk_version}}
      working-directory: ${{ github.workspace }}

    - name: Update draft release to false
      run: |
        gh release edit $MIMI_SDK_VERSION --tag $MIMI_SDK_VERSION --target main --draft=false --notes-file Changelog.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MIMI_SDK_VERSION: ${{steps.set_env_variables.outputs.sdk_version}}
      working-directory: ${{ github.workspace }}

  # notify:
  #   needs: release
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Send Slack message to prod-releases channel
  #     uses: slackapi/slack-github-action@v1.24.0
  #     with:
  #       payload: |
  #         {
  #           "channel": "C01JDQES01G",
  #           "text": "🚀 Mimi SDK v${{needs.release.outputs.sdk_version}} for iOS is now available",
  #           "blocks": [
  #             {	
  #               "type": "header",
  #               "text": {
  #                 "type": "plain_text",
  #                 "text": "🚀 Mimi SDK v${{needs.release.outputs.sdk_version}} for iOS is now available",
  #                 "emoji": true
  #               }
  #             },
  #             {
  #               "type": "section",
  #               "text": {
  #                 "type": "mrkdwn",
  #                 "text": "<https://github.com/MimiHearingTechnologies/SDK-iOS-Binaries/releases/tag/${{needs.release.outputs.sdk_version}}|*View on GitHub*>"
  #               }
  #             }
  #           ]
  #         }
  #     env:
  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #       SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  #   - name: Send Slack message to prod-mobile-sdk channel
  #     uses: slackapi/slack-github-action@v1.24.0
  #     with:
  #       payload: |
  #         {
  #           "channel": "C01CJUL8AM6",
  #           "text": "🚀 Mimi SDK v${{needs.release.outputs.sdk_version}} for iOS is now available",
  #           "blocks": [
  #             {	
  #               "type": "header",
  #               "text": {
  #                 "type": "plain_text",
  #                 "text": "🚀 Mimi SDK v${{needs.release.outputs.sdk_version}} for iOS is now available",
  #                 "emoji": true
  #               }
  #             },
  #             {
  #               "type": "section",
  #               "text": {
  #                 "type": "mrkdwn",
  #                 "text": "<https://github.com/MimiHearingTechnologies/SDK-iOS-Binaries/releases/tag/${{needs.release.outputs.sdk_version}}|*View on GitHub*>"
  #               }
  #             }
  #           ]
  #         }
  #     env:
  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #       SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
