name: CI release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.set_version.outputs.MIMI_SDK_VERSION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - id: set_version
      name: Set environment variables
      run: |
        echo "MIMI_SDK_VERSION=$(grep -oP 'MIMI_SDK_VERSION=\K[^ ]+' Version.config)" >> $GITHUB_ENV
        echo "MIMI_SDK_VERSION=$(grep -oP 'MIMI_SDK_VERSION=\K[^ ]+' Version.config)" >> "$GITHUB_OUTPUT"
      working-directory: ${{ github.workspace }}
      
    - name: Unarchive zip file
      run: |
        rm -rf artifacts
        mkdir artifacts
        unzip MimiSDK-$MIMI_SDK_VERSION.zip -d artifacts
      working-directory: ${{ github.workspace }}

    - name: Create draft release
      run: |
        body=$(<Changelog.md)
        gh release create $MIMI_SDK_VERSION -t "MimiSDK v$MIMI_SDK_VERSION" -F Changelog.md --draft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{ github.workspace }}

    - name: Upload artifacts to release
      run: |
        gh release upload $MIMI_SDK_VERSION "MimiSDK-$MIMI_SDK_VERSION.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{ github.workspace }}

    - name: Remove zip file and unnecessary files
      run: |
        rm -rf MimiSDK-$MIMI_SDK_VERSION.zip Version.config Changelog.md
      working-directory: ${{ github.workspace }}

    - name: Commit and push changes
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "Release [skip ci]"
        git push
      env:
        token: ${{ secrets.GH_TOKEN }}
      working-directory: ${{ github.workspace }}

    - name: Update draft release to false
      run: |
        gh release edit $MIMI_SDK_VERSION --draft=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{ github.workspace }}

  notify:
    needs: release
    runs-on: ubuntu-latest

    steps:
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "channel": "C01JDQES01G",
            "text": "🚀 Mimi SDK v${{needs.release.outputs.output1}} for iOS is now available",
            "blocks": [
              {	
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "🚀 Mimi SDK v${{needs.release.outputs.output1}} for iOS is now available",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://github.com/MimiHearingTechnologies/SDK-iOS-Binaries-Test/releases/tag/${{needs.release.outputs.output1}}|*View on GitHub*>"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


  
